#!/bin/bash

#Make a clean build
if [ -e Makefile ];
then
    make -j10 distclean
fi;

#Make a clean install always
if [ -d /tmp/arm-eabi ]
then
    rm -rf /tmp/arm-eabi
fi;

#Build Configuration
./configure --prefix=/tmp/arm-eabi --target=arm-eabi --host=x86_64-linux-gnu --build=x86_64-linux-gnu --program-transform-name='s&^&arm-eabi-&' --with-gcc-version=SaberMod --with-binutils-version=2.21 --with-gmp-version=4.3.2 --with-mpfr-version=2.4.2 --with-mpc-version=1.0.1 --with-gdb-version=7.3.x --with-sysroot=/ --with-host-libstdcxx='-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm' --enable-threads=single;

#Build the toolchain
make -j10;

#Install the toolchain
make install;
