#!/bin/bash

#Make a clean build
if [ -e Makefile ];
then
    make -j10 distclean
fi;

#Make a clean install always
if [ -d /home/sparksco/android/arm-eabi ]
then
    rm -rf /home/sparksco/android/arm-eabi
fi;

#Build Configuration
./configure --prefix=/home/sparksco/android/arm-eabi --target=arm-eabi --host=x86_64-linux-gnu --build=x86_64-linux-gnu --program-transform-name='s&^&arm-eabi-&' --with-gcc-version=SaberMod --with-binutils-version=2.22 --with-gmp-version=5.0.5 --with-mpfr-version=3.1.1 --with-mpc-version=1.0.1 --with-gdb-version=7.5.1 --with-sysroot=/ --with-host-libstdcxx='-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm' --enable-threads=single;

#Build the toolchain
make -j10;

#Install the toolchain twice to make sure everything gets installed
make -j10 install && make -j10 install
