#!/bin/bash

panic ()
{
    echo "ERROR: $@"
    exit 1
}

panic "**************ERROR*****************
       **************ERROR*****************
       **************ERROR*****************
                                           
       Sorry your build failed because
       cloog failed to build the required
       libraries.  Please uninstall any
       cloog-isl packages such as
       libcloog-isl-dev
                                           
       **************ERROR*****************
       **************ERROR*****************
       **************ERROR*****************";
